services: 
  ceph: 
    build: .  
    container_name: ceph

    stdin_open: true # docker run -i
    tty: true        # docker run -t

    privileged: true
    cap_add:
      - SYS_ADMIN

    volumes:
      - ./volume/:/var/lib/containers/


