services: 
  ceph: 
    build: .  
    container_name: ceph
    ports: 
      - 3300:3300
      - 6789:6789

    stdin_open: true # docker run -i
    tty: true        # docker run -t

    privileged: true
    cap_add:
      - SYS_ADMIN




